#ifndef VOLTAGE_H
#define VOLTAGE_H

#define SUPPLY_DIVIDER_UPPER1_OHMS 100000.0f
#define SUPPLY_DIVIDER_UPPER2_OHMS 90000.0f
#define SUPPLY_DIVIDER_LOWER_OHMS 10000.0f
#define SUPPLY_VOLTAGE_SCALE \
	((SUPPLY_DIVIDER_UPPER1_OHMS + SUPPLY_DIVIDER_UPPER2_OHMS + \
	  SUPPLY_DIVIDER_LOWER_OHMS) / SUPPLY_DIVIDER_LOWER_OHMS)

/* Nominal STC8H internal reference signal measured on ADC channel 15. */
#define ADC_REFERENCE_VOLTS 1.19f

#endif
